groups:
- name: enterprise-service-alerts
  rules:
  # Alert if any service has a high failure rate
  - alert: HighErrorRate
    # FIX: Added 'sum' and 'by (service_name)' to ensure the 2% is calculated per service
    expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by (service_name) / sum(rate(http_requests_total[5m])) by (service_name) > 0.02
    for: 2m
    labels:
      severity: critical
      team: backend
    annotations:
      summary: "High Error Rate on {{ $labels.service_name }}"
      description: "Service {{ $labels.service_name }} is returning >2% errors for more than 2 minutes. Immediate rollback may be required."

  # Alert if service latency exceeds 500ms
  - alert: SlowResponseTime
    # FIX: Corrected syntax for histogram_quantile to ensure it maps correctly to service_name
    expr: histogram_quantile(0.95, sum by (le, service_name) (rate(http_request_duration_seconds_bucket[5m]))) > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Latency spike on {{ $labels.service_name }}"
      description: "95th percentile latency for {{ $labels.service_name }} is above 500ms."
